training_modifiers:
  
  - !EpochRangeModifier
    start_epoch: 0
    end_epoch: 300
  
  - !SetLearningRateModifier
    constant_logging: False
    start_epoch: 0
    end_epoch: 200
    learning_rate: 0.0001
    log_types: __ALL__

  - !LearningRateFunctionModifier
    start_epoch: 200
    end_epoch: 300
    lr_func: cosine
    init_lr: 0.0001
    final_lr: 0.000001
  
pruning_modifiers:

  - !GlobalMagnitudePruningModifier
      init_sparsity: 0.0
      final_sparsity: 0.75
      start_epoch: 0
      end_epoch: 200    
      update_frequency: 5
      params: ['re:(.*blocks.*.attn.qkv.weight)|(.*blocks.*.attn.proj.weight)|(.*blocks.*.mlp.fc.*weight)'] 
      global_sparsity: True
      inter_func: cubic
      leave_enabled: True
      mask_type: unstructured

  - !GlobalMagnitudePruningModifier
      init_sparsity: 0.75
      final_sparsity: 0.75
      start_epoch: 200
      end_epoch: 300    
      update_frequency: 100
      params: ['re:(.*blocks.*.attn.qkv.weight)|(.*blocks.*.attn.proj.weight)|(.*blocks.*.mlp.fc.*weight)'] 
      global_sparsity: True
      inter_func: linear
      leave_enabled: True
      mask_type: unstructured